spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d6dplpctgctc73f925pg-a.oregon-postgres.render.com/eccomerce_4bf8}
spring.datasource.username=${DB_USER:eccomerce_4bf8_user}
spring.datasource.password=${DB_PASSWORD:YsmspBuB4au1PnR1Vvx99fxnpwyZP6Eu}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
